import { CallManager } from './call/call-manager';
import { startCallHandler, endCallHandler, statusHandler, refreshTokenHandler } from './http/call-api';
import { chatCompletionsHandler } from './http/chat-api';
import type { PluginConfig } from './types/config';
import { readWorkspaceFile, writeWorkspaceJson, resolveWorkspacePath } from './context/loader';
import { FastAgentFactory } from './agent/factory';
import { IFastAgent } from './agent/types';
import { mockCallbackHandler } from './http/mock-webhook';
import { callContextStorage } from './context/ctx';
import * as dotenv from 'dotenv';
import { EventEmitter } from 'events';

// 加载 .env (显式指定路径，确保作为 OpenClaw 插件加载时也能找到)
import * as path from 'path';
dotenv.config({ path: path.join(__dirname, '../.env') });

// 全局通知总线，用于模拟环境的异步通知推送
const notificationBus = new EventEmitter();
notificationBus.setMaxListeners(100);

// [V1.9.0] 记录活跃的仿真会话 (SSE)，用于无目标播报时的广播fallback
const activeSimSessions = new Set<string>();

// 模拟 OpenClaw 的 PluginAPI 接口类型
interface PluginAPI {
    registerHttpRoute(options: { path: string; auth?: string; match?: string; handler: (req: any, res: any) => Promise<void> | void }): void;
    registerTool(options: any): void;
    // ... 可以扩充其他相关内容
}

/**
 * OpenClaw Plugin 入口函数 
 * (OpenClaw 加载插件后会自动调用 register() )
 */
export function register(api: PluginAPI, config: PluginConfig = {} as any) {
    console.log('[VoiceGateway] Registering Plugin with Config:', config);

    // 1. 初始化通话状态机和 ZEGO API Client
    const workspaceRoot = resolveWorkspacePath(config?.advanced?.httpAuthToken === 'none' ? './demo_workspace' : undefined);
    const callManager = new CallManager(config || {} as any);

    // 初始化 FastAgent (注入环境变量中的专属 Fast Agent 配置，独立于 OpenClaw)
    const fastAgent: IFastAgent = FastAgentFactory.create({
        ...(config || {}),
        llm: {
            ...(config?.llm || {}),
            apiKey: process.env.FAST_AGENT_API_KEY || process.env.BAILIAN_API_KEY || config?.llm?.apiKey,
            baseUrl: process.env.FAST_AGENT_BASE_URL || process.env.BAILIAN_BASE_URL || config?.llm?.baseUrl,
            model: process.env.FAST_AGENT_MODEL || process.env.BAILIAN_MODEL || config?.llm?.model
        },
        fastAgent: {
            version: process.env.FAST_AGENT_VERSION || config?.fastAgent?.version || 'v2',
            slcModel: process.env.FAST_AGENT_SLC_MODEL || 'qwen-turbo',
            sleModel: process.env.FAST_AGENT_SLE_MODEL || process.env.FAST_AGENT_MODEL || 'qwen-plus',
            slcBaseUrl: config?.fastAgent?.slcBaseUrl,
            sleBaseUrl: config?.fastAgent?.sleBaseUrl
        }
    }, workspaceRoot);

    // 🚀 安全扫雷机制 (Reboot GC)：防止宿主奔溃和发版残留导致漏费
    // 🚀 安全扫雷机制 (Reboot GC)
    (async () => {
        try {
            // 🌟 动态写入 SKILL.md 到工作区，最高优先级暴露给主 Agent
            const skillContent = `---
name: voice-integration
description: 掌握如何接管、查询和主动通过外呼电话与用户进行语音沟通的技能。
---

# 语音通话接管能力 (Voice Integration Skill)

当用户通过语音门户触发了一项复杂的后台耗时任务（如："帮我给张三发个邮件"）时，网关代理会把这个任务委托(delegate)给本意图。

## 关键工具
1. \`voice_speak\`: 主动播报进展或结果（支持 text, delay, userId, strategy）。
2. \`voice_status\`: 查询是否有活跃通话。

## 场景规范
1. **耗时任务（长任务）**:
   - 收到任务后，立刻调用 \`voice_speak\` 说："正在处理，请稍候。"。
   - 任务完成后，**必须**调用 \`voice_speak\` 播报结果。
2. **异步提醒/闹钟 (优先方式)**:
   - 如果用户说 "30秒后提醒我"，你应该直接调用 \`voice_speak\` 并设置 \`delay: 30\`。
   - 示例：\`voice_speak({ text: "您要的30秒提醒到了", delay: 30 })\`。
   - 这种方式最稳定，由网关插件在持久化进程中维护倒计时。
3. **状态检查**: 任务结束后或时间到达，如果 \`voice_status\` 显示用户不在通话中，\`voice_speak\` 会尝试发送文本通知（仿真模式下也能收到）。
`;
            
            const pFs = require('fs/promises');
            const pPath = require('path');
            const skillsDir = pPath.join(workspaceRoot, 'skills');
            const skillFile = pPath.join(skillsDir, 'voice-gateway.md');
            await pFs.mkdir(skillsDir, { recursive: true });
            
            const finalContent = `<!-- Auto-generated by ZEGO Voice Gateway, do not edit manually unless allowSkillOverride is disabled -->\n${skillContent}`;
            await pFs.writeFile(skillFile, finalContent, 'utf-8');
            console.log(`[VoiceGateway] Injected SKILL documentation to: ${skillFile}`);

            const rawData = await readWorkspaceFile(workspaceRoot, 'call_states.json');
            if (rawData) {
                let data = JSON.parse(rawData);
                if (data.instances && Array.isArray(data.instances) && data.instances.length > 0) {
                    console.warn(`[VoiceGateway] ⚠️ DETECTED ${data.instances.length} GHOST INSTANCES. Sweeping...`);
                    for (const agentId of data.instances) {
                        try { await callManager.api.deleteAgentInstance(agentId); } catch(e) {}
                    }
                }
                await writeWorkspaceJson(workspaceRoot, 'call_states.json', { instances: [] });
            }
        } catch (error) {
            console.error('[VoiceGateway] Startup task failed:', error);
        }
    })();

    // 一次性调用 ZEGO 模板注册接口，将咱们提供的 http endpoint 备案给 ZEGO 云
    // Phase 1 MVP 假定本机调试地址为内网穿透或者本机的 openclaw web port 18789
    // 如果设置了 PUBLIC_URL 环境变量，则优先使用，否则 fallback 到之前的硬编码进行占位
    const publicBase = process.env.PUBLIC_URL || 'https://wcmsx-185-220-238-40.a.free.pinggy.link';
    const myLlmUrl = `${publicBase}/voice-gateway/chat/completions`;

    console.log(`[VoiceGateway] Registering Agent with Callback URL: ${myLlmUrl}`);

    // 初始化注册逻辑 (不 block 启动过程)
    const agentParams = {
        llmUrl: myLlmUrl,
        llm: {
            apiKey: process.env.BAILIAN_API_KEY || config?.llm?.apiKey || '',
            model: process.env.BAILIAN_MODEL || config?.llm?.model || 'qwen3.5-plus',
            baseUrl: process.env.BAILIAN_BASE_URL || config?.llm?.baseUrl || 'https://dashscope.aliyuncs.com/compatible-mode/v1'
        },
        tts: {
            vendor: config?.tts?.vendor || 'ByteDance',
            appId: config?.tts?.appId || 'zego_test',
            token: config?.tts?.token || 'zego_test',
            voiceType: config?.tts?.voiceType || 'zh_female_wanwanxiaohe_moon_bigtts'
        },
        asr: config?.asr
    };

    if (agentParams.llm.apiKey) {
        callManager.api.registerAgent(agentParams as any).catch(async (err: any) => {
            if (err.message?.includes('410001008')) {
                console.log('[VoiceGateway] Agent already exists, updating configuration instead...');
                try {
                    await callManager.api.updateAgent(agentParams as any);
                    console.log('[VoiceGateway] Agent configuration updated successfully.');
                } catch (updateErr: any) {
                    console.error('[VoiceGateway] Failed to update existing agent:', updateErr.message);
                }
            } else {
                console.error('[VoiceGateway] Failed to register agent on startup:', err.message);
            }
        });
    } else {
        console.warn('[VoiceGateway] Skipping agent registration: Missing LLM API Key.');
    }

    api.registerHttpRoute({
        path: '/voice-gateway/chat/completions',
        auth: 'none', // 暂时设为 none 以确保测试阶段 ZEGO 回调能通过
        handler: async (req: any, res: any) => {
            const instanceId = req.body?.agent_info?.agent_instance_id || 'unknown';
            console.log(`[VoiceGateway] [Incoming] SSE Request for Instance: ${instanceId}`);
            console.log(`[VoiceGateway] [Debug] Raw Body: ${JSON.stringify(req.body)}`);
            console.log(`[VoiceGateway] [Debug] Headers: ${JSON.stringify(req.headers)}`);

            if (!req.body || !req.body.messages) {
                console.error(`[VoiceGateway] [Error] Missing body or messages array! Full Body:`, req.body);
            }

            await callContextStorage.run({ 
                callId: instanceId, 
                userId: req.body?.agent_info?.user_id || 'unknown', 
                startTime: Date.now(), 
                metadata: {} 
            }, async () => {
                await chatCompletionsHandler(callManager, config, fastAgent)(req, res);
            });
        }
    });

    // 3. 注册通话管理 API 接口
    api.registerHttpRoute({
        path: '/voice/start-call',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: startCallHandler(callManager, config.zego)
    });

    api.registerHttpRoute({
        path: '/voice/end-call',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: endCallHandler(callManager)
    });

    api.registerHttpRoute({
        path: '/voice/status',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: statusHandler(callManager)
    });

    api.registerHttpRoute({
        path: '/voice/refresh-token',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: refreshTokenHandler(callManager, config.zego)
    });

    // 🚀 [New] 文本对话互动接口 (Fast Agent Text MVP)
    const textChatHistories = new Map<string, any[]>();
    api.registerHttpRoute({
        path: '/voice/text-chat',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: async (req: any, res: any) => {
            const { message, sessionId, version: requestVersion } = req.body;
            const callId = sessionId || `text-chat-${Date.now()}`;
            
            res.setHeader('Content-Type', 'text/event-stream');
            res.setHeader('Cache-Control', 'no-cache');
            res.setHeader('Connection', 'keep-alive');

            const history = textChatHistories.get(callId) || [];
            const currentMessages = [...history, { role: 'user', content: message }];

            // 动态选择版本
            let currentAgent = fastAgent;
            if (requestVersion && requestVersion !== (config.fastAgent?.version || 'v2')) {
                console.log(`[TextChat] Dynamically switching to version: ${requestVersion}`);
                currentAgent = FastAgentFactory.create({
                    ...config,
                    fastAgent: { ...config.fastAgent, version: requestVersion }
                }, workspaceRoot);
            }

            await callContextStorage.run({ callId, userId: 'tester', startTime: Date.now(), metadata: {} }, async () => {
                let fullReply = "";
                await currentAgent.process(currentMessages, (chunk: any) => {
                    if (chunk.type === 'text' || chunk.type === 'filler') {
                        fullReply += chunk.content;
                    }
                    res.write(`data: ${JSON.stringify(chunk)}\n\n`);
                }, async (notifyText: string) => {
                    // 对于模拟器，将后台异步通知通过总线推送，并记录到历史中
                    console.log(`[TextChat][Notification] ${callId}: ${notifyText}`);
                    
                    const hist = textChatHistories.get(callId) || [];
                    hist.push({ role: 'assistant', content: notifyText });
                    textChatHistories.set(callId, hist);

                    // 核心：推送到通知总线
                    notificationBus.emit('notify', { sessionId: callId, text: notifyText });
                });
                
                // 更新历史
                history.push({ role: 'user', content: message });
                history.push({ role: 'assistant', content: fullReply });
                textChatHistories.set(callId, history.slice(-20)); // 保留最近 20 条
            });
            res.write('data: [DONE]\n\n');
            res.end();
            
            // 如果是临时创建的实例，需要销毁以释放定时器
            if (currentAgent !== fastAgent) {
                currentAgent.destroy();
            }
        }
    });

    // 🚀 [New] 仿真背景消息总线 (用于测试面板异步接收任务结果)
    api.registerHttpRoute({
        path: '/voice/internal/notify',
        match: 'POST',
        handler: async (req, res) => {
            const { sessionId, text } = req.body;
            console.log(`[Internal Notify] Received: "${text}" for session: ${sessionId || 'broadcast'}`);
            
            if (sessionId) {
                notificationBus.emit('notify', { sessionId, text });
            } else {
                // 如果没有指定 ID，向所有仿真会话广播
                for (const simId of activeSimSessions) {
                    notificationBus.emit('notify', { sessionId: simId, text });
                }
            }
            res.json({ success: true });
        }
    });

    api.registerHttpRoute({
        path: '/voice/events',
        auth: 'none',
        handler: async (req: any, res: any) => {
            const { sessionId } = req.query;
            if (!sessionId) return res.status(400).send('Missing sessionId');

            res.setHeader('Content-Type', 'text/event-stream');
            res.setHeader('Cache-Control', 'no-cache');
            res.setHeader('Connection', 'keep-alive');
            res.flushHeaders?.();

            activeSimSessions.add(sessionId);

            // 每 15 秒发送一个心跳，防止连接断开
            const heartbeat = setInterval(() => {
                res.write(`: heartbeat\n\n`);
            }, 15000);

            const onNotify = (data: any) => {
                if (data.sessionId === sessionId) {
                    res.write(`data: ${JSON.stringify({ type: 'notification', content: data.text })}\n\n`);
                }
            };

            notificationBus.on('notify', onNotify);

            req.on('close', () => {
                clearInterval(heartbeat);
                notificationBus.off('notify', onNotify);
                activeSimSessions.delete(sessionId);
            });

            // 发送一个初始连接成功信号
            res.write(`data: ${JSON.stringify({ type: 'system', content: 'Event bus connected' })}\n\n`);
        }
    });

    // 🚀 [New] 模拟主 Agent 回调
    api.registerHttpRoute({
        path: '/voice/mock-callback',
        auth: 'none',
        handler: mockCallbackHandler(callManager)
    });

    console.log('[VoiceGateway] Plugin routes registered successfully.');

    // 4. 注册外部工具给 OpenClaw 主 Agent
    const { Type } = require('@sinclair/typebox');

    api.registerTool({
        name: 'voice_speak',
        description: '通过语音通话向用户主动播报一段文本。适用于后台耗时任务完成时的通知。',
        parameters: Type.Object({
            userId: Type.String({ description: '要通知的用户 ID。如果不知道可以留空，将尝试向最近活跃的通话广播。' }),
            text: Type.String({ description: '要语音播报的文本，尽量简短口语化，不要超过 300 字。' }),
            delay: Type.Optional(Type.Number({ description: '延迟播报的秒数。例如 5 表示 5 秒后播报。适用于异步提醒。' })),
            priority: Type.Optional(Type.Union([Type.Literal('High'), Type.Literal('Medium'), Type.Literal('Low')])),
            strategy: Type.Optional(Type.Union([Type.Literal('interrupt'), Type.Literal('queue')], { description: 'interrupt 适用于紧急通知（如“系统错误，即将挂断”）。queue 适用于异步任务完成后的提醒（如“您刚才让我查的天气已经有了”）' }))
        }),
        execute: async (executionId: string, params: any) => {
            console.log(`[voice_speak] [EXEC] ID: ${executionId} | Text: "${params.text}" | Delay: ${params.delay || 0}s | Target: ${params.userId || 'any'}`);
            
            const doSpeak = async () => {
                // 原有的 speak 逻辑封装在这里
                console.log(`[voice_speak] [DO_SPEAK] Text: "${params.text}"`);
            
            // 优先级：参数指定ID > RTC活跃通话ID > 仿真会话ID
            const tgtUserId = params.userId 
                || Array.from(callManager['activeCalls'].keys())[0]
                || Array.from(activeSimSessions.keys())[0];

            console.log(`[voice_speak] Resolved target user ID: ${tgtUserId}`);

            const activeInstanceId = tgtUserId ? callManager.getActiveInstanceId(tgtUserId) : null;

            // [仿真支持] 如果没有找到活跃的 RTC 通话，尝试推送到仿真总线 (SSE)
            if (!activeInstanceId) {
                console.log(`[voice_speak] No active RTC call found for ${tgtUserId}, checking simulation bus... (Sessions: ${Array.from(activeSimSessions).join(', ')})`);
                if (tgtUserId && activeSimSessions.has(tgtUserId)) {
                    console.log(`[voice_speak] 🚀 Emitting to simulation bus for session: ${tgtUserId}`);
                    notificationBus.emit('notify', { sessionId: tgtUserId, text: params.text });
                    return { success: true, message: `已推送到仿真终端 (Simulation Mode)。` };
                }
                
                // Final fallback: if we have any sim sessions but IDs don't match or were lost, broadcast to all
                if (activeSimSessions.size > 0) {
                    const firstSimId = Array.from(activeSimSessions)[0];
                    console.log(`[voice_speak] 🚀 Broadcasting to first available simulation session: ${firstSimId}`);
                    notificationBus.emit('notify', { sessionId: firstSimId, text: params.text });
                    return { success: true, message: `已广播到仿真终端。` };
                }

                // [CLI 转发机制] 如果本地没有找到任何会话，说明可能是在独立的 CLI 进程中运行
                // 尝试向本地 Gateway 的内部端口发送通知，让持久化的 Gateway 进程来转发
                try {
                    console.log('[voice_speak] 🔗 CLI Forwarding: No local sessions, trying Gateway ports...');
                    const ports = [18791, 18790];
                    const paths = ['/voice-gateway/voice/internal/notify', '/voice/internal/notify'];
                    const http = require('http');
                    const postData = JSON.stringify({ sessionId: tgtUserId, text: params.text });

                    for (const port of ports) {
                        for (const path of paths) {
                            try {
                                const options = {
                                    hostname: '127.0.0.1',
                                    port: port,
                                    path: path, 
                                    method: 'POST',
                                    headers: {
                                        'Content-Type': 'application/json',
                                        'Content-Length': Buffer.byteLength(postData)
                                    },
                                    timeout: 500
                                };

                                const req = http.request(options, (res: any) => {
                                    console.log(`[voice_speak] 🔗 Forwarded to ${port}${path} | Status: ${res.statusCode}`);
                                    if (res.statusCode === 200) {
                                        console.log(`[voice_speak] ✅ Successfully delivered to ${port}${path}`);
                                    }
                                });
                                req.on('error', (err: any) => {
                                    console.log(`[voice_speak] ❌ Failed to forward to ${port}${path}: ${err.message}`);
                                });
                                req.write(postData);
                                req.end();
                            } catch (e) {}
                        }
                    }
                    
                    return { success: true, message: `通知已尝试转发至网关服务。` };
                } catch (e: any) {
                    console.error('[voice_speak] CLI Forwarding fatal error:', e.message);
                }

                return { success: false, error: '当前没有活跃的语音通话或仿真会话。' };
            }

                try {
                    const zegoStrategy = params.strategy === 'queue' ? 'Enqueue' : 'ClearAndInterrupt';
                    // 1. 发送语音
                    await callManager.api.sendAgentInstanceTTS(activeInstanceId, params.text, params.priority || 'Medium', zegoStrategy);
                    // 2. [V1.9.0] 发送文本/字幕内容，确保客户端音画同步
                    await callManager.api.addAgentInstanceMsg(activeInstanceId, 'assistant', params.text);
                    // 3. 同时推送到仿真总线 (用于双端监控)
                    notificationBus.emit('notify', { sessionId: tgtUserId, text: params.text });
                    
                    return { success: true, message: `已成功向用户发送语音播报。` };
                } catch (err: any) {
                    return { success: false, error: `语音播报发送失败: ${err.message}` };
                }
            };

            if (params.delay && params.delay > 0) {
                console.log(`[voice_speak] Scheduling deferred talk in ${params.delay}s...`);
                setTimeout(doSpeak, params.delay * 1000);
                return { success: true, message: `已成功预约在 ${params.delay} 秒后提醒。` };
            } else {
                return await doSpeak();
            }
        }
    });

    api.registerTool({
        name: 'voice_status',
        description: '查询当前所有活跃中的语音通话状态。',
        parameters: Type.Object({}),
        execute: async () => {
            const calls = Array.from(callManager['activeCalls'].values()).map(c => ({
                userId: c.userId,
                roomId: c.roomId,
                status: c.status,
                liveMinutes: Math.round((Date.now() - c.startTime.getTime()) / 60000)
            }));
            return { activeCalls: calls, total: calls.length };
        }
    });

    console.log('[VoiceGateway] Agent Tools registered successfully.');

    // TODO: 定时清理任务，清除没有正常结束的僵尸连接
}
