import { CallManager } from './call/call-manager';
import { startCallHandler, endCallHandler, statusHandler, refreshTokenHandler } from './http/call-api';
import { chatCompletionsHandler } from './http/chat-api';
import type { PluginConfig } from './types/config';
import { readWorkspaceFile, writeWorkspaceJson } from './context/loader';

// 模拟 OpenClaw 的 PluginAPI 接口类型
interface PluginAPI {
    registerHttpRoute(options: { path: string; auth?: string; match?: string; handler: (req: any, res: any) => Promise<void> | void }): void;
    registerTool(options: any): void;
    // ... 可以扩充其他相关内容
}

/**
 * OpenClaw Plugin 入口函数 
 * (OpenClaw 加载插件后会自动调用 register() )
 */
export function register(api: PluginAPI, config: PluginConfig) {
    console.log('[VoiceGateway] Registering Plugin with Config:', config);

    // 1. 初始化通话状态机和 ZEGO API Client
    const callManager = new CallManager(config);

    // 🚀 安全扫雷机制 (Reboot GC)：防止宿主奔溃和发版残留导致漏费
    // setTimeout 延迟 5 秒执行，绝不阻碍 OpenClaw 主 Agent 的启动引导流程
    setTimeout(async () => {
        try {
            const rawData = await readWorkspaceFile(callManager.workspaceRoot, 'call_states.json');
            if (!rawData) return;

            let data: any = {};
            try {
                data = JSON.parse(rawData);
            } catch (e) {
                console.error('[VoiceGateway] Invalid call_states.json syntax, ignoring GC.', e);
                return;
            }

            if (data.instances && Array.isArray(data.instances) && data.instances.length > 0) {
                console.warn(`[VoiceGateway] ⚠️ DETECTED ${data.instances.length} GHOST INSTANCES from previous run. Sweeping safely...`);

                // 并发节流控制：每次最多并发清理 5 个，防止把 ZEGO API 打挂或被封禁
                const batchSize = 5;
                for (let i = 0; i < data.instances.length; i += batchSize) {
                    const batch = data.instances.slice(i, i + batchSize);
                    await Promise.allSettled(batch.map(async (agentId: string) => {
                        try {
                            await callManager.api.deleteAgentInstance(agentId);
                            console.log(`[VoiceGateway] Swept ghost instance: ${agentId}`);
                        } catch (e: any) {
                            console.error(`[VoiceGateway] Failed to sweep ${agentId}: ${e.message}`);
                        }
                    }));
                }
            }
            // 完全清空状态文件
            await writeWorkspaceJson(callManager.workspaceRoot, 'call_states.json', { instances: [] });
            console.log('[VoiceGateway] Reboot GC finished successfully.');

            // 🌟 动态写入 SKILL.md 到工作区，最高优先级暴露给主 Agent
            const skillContent = `---
name: voice-integration
description: 掌握如何接管、查询和主动通过外呼电话与用户进行语音沟通的技能。
---

# 语音通话接管能力 (Voice Integration Skill)

当用户通过语音门户触发了一项复杂的后台耗时任务（如："帮我给张三发个邮件"）时，网关代理会把这个任务委托(delegate)给本意图，并且用户当前仍在电话线上等待。

由于生成或执行报告可能需要好几秒甚至几十秒，这期间不能让电话那头的人干等着。你需要使用本技能提供的能力来管理通话体验。

## 关键工具
1. \`voice_speak\`: 主动向还在电话线上的用户语音播报进展或完成状态。
2. \`voice_status\`: 查询当前是否有活跃电话，以及对应的 userId。

## 执行规范
1. **立即安抚**: 收到长委托时，如果觉得耗时，可以立刻调用 \`voice_speak\` 播报："我正在为您执行任务，请稍候。"。
2. **结果触达**: 任务完成后，**必须**：
   - 将文字版的执行结果写入 Memory 日志（供日后文本回顾）。
   - **同时极度关键**：调用 \`voice_speak\` 主动用语音告诉用户："您的任务我已经处理完毕了，结果是..."。
3. 如果 \`voice_status\` 显示没有活跃电话了，就只写 Memory，不用说话。
`;

            const pFs = require('fs/promises');
            const pPath = require('path');
            const skillsDir = pPath.join(callManager.workspaceRoot, 'skills');
            const skillFile = pPath.join(skillsDir, 'voice-gateway.md');
            await pFs.mkdir(skillsDir, { recursive: true });

            let fileExists = false;
            try {
                await pFs.access(skillFile);
                fileExists = true;
            } catch (err) { }

            const allowOverride = config.advanced?.allowSkillOverride !== false;

            if (fileExists && !allowOverride) {
                console.warn('[VoiceGateway] [WARN] 检测到现存的 voice-gateway.md，跳过覆盖以保护自定义配置。');
            } else {
                const finalContent = `<!-- Auto-generated by ZEGO Voice Gateway, do not edit manually unless allowSkillOverride is disabled -->\n${skillContent}`;
                await pFs.writeFile(skillFile, finalContent, 'utf-8');
                console.log('[VoiceGateway] Injected SKILL documentation to workspace skills directory.');
            }

        } catch (error) {
            // 最外层严防死守，绝不会因为未捕获异常导致 OpenClaw 主进程奔溃
            console.error('[VoiceGateway] Fatal ERROR during Reboot GC:', error);
        }
    }, 5000);

    // 一次性调用 ZEGO 模板注册接口，将咱们提供的 http endpoint 备案给 ZEGO 云
    // Phase 1 MVP 假定本机调试地址为内网穿透或者本机的 openclaw web port 18789
    // 在真实环境应从 config 或 ctx 中取
    const myLlmUrl = `http://localhost:18789/chat/completions`;

    // 初始化注册一次 (不 block 启动过程)
    callManager.api.registerAgent({
        llmUrl: myLlmUrl,
        llm: config.llm,
        tts: config.tts,
        asr: config.asr
    }).catch(err => console.error('[VoiceGateway] Failed to register agent on startup:', err));

    // 2. 注册大模型的拦截 Endpoint
    api.registerHttpRoute({
        path: '/chat/completions',
        auth: config.advanced?.httpAuthToken || 'none', // 生产应设为 token 避免盗刷
        handler: chatCompletionsHandler(callManager, config)
    });

    // 3. 注册通话管理 API 接口
    api.registerHttpRoute({
        path: '/voice/start-call',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: startCallHandler(callManager, config.zego)
    });

    api.registerHttpRoute({
        path: '/voice/end-call',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: endCallHandler(callManager)
    });

    api.registerHttpRoute({
        path: '/voice/status',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: statusHandler(callManager)
    });

    api.registerHttpRoute({
        path: '/voice/refresh-token',
        auth: config.advanced?.httpAuthToken || 'none',
        handler: refreshTokenHandler(callManager, config.zego)
    });

    console.log('[VoiceGateway] Plugin routes registered successfully.');

    // 4. 注册外部工具给 OpenClaw 主 Agent
    const { Type } = require('@sinclair/typebox');

    api.registerTool({
        name: 'voice_speak',
        description: '通过语音通话向用户主动播报一段文本。适用于后台耗时任务完成时的通知。',
        parameters: Type.Object({
            userId: Type.String({ description: '要通知的用户 ID。如果不知道可以留空，将尝试向最近活跃的通话广播。' }),
            text: Type.String({ description: '要语音播报的文本，尽量简短口语化，不要超过 300 字。' }),
            priority: Type.Optional(Type.Union([Type.Literal('High'), Type.Literal('Medium'), Type.Literal('Low')])),
            strategy: Type.Optional(Type.Union([Type.Literal('interrupt'), Type.Literal('queue')], { description: 'interrupt 适用于紧急通知（如“系统错误，即将挂断”）。queue 适用于异步任务完成后的提醒（如“您刚才让我查的天气已经有了”）' }))
        }),
        execute: async (executionId: string, params: any) => {
            const tgtUserId = params.userId || Array.from(callManager['activeCalls'].keys())[0];
            if (!tgtUserId) {
                return { success: false, error: '当前没有活跃的首选语音通话' };
            }

            const activeInstanceId = callManager.getActiveInstanceId(tgtUserId);
            if (!activeInstanceId) {
                return { success: false, error: `用户 ${tgtUserId} 当前没有活跃的语音连接` };
            }

            try {
                const zegoStrategy = params.strategy === 'queue' ? 'Enqueue' : 'ClearAndInterrupt';
                await callManager.api.sendAgentInstanceTTS(activeInstanceId, params.text, params.priority || 'Medium', zegoStrategy);
                return { success: true, message: `已成功向用户发送语音播报。` };
            } catch (err: any) {
                return { success: false, error: `语音播报发送失败: ${err.message}` };
            }
        }
    });

    api.registerTool({
        name: 'voice_status',
        description: '查询当前所有活跃中的语音通话状态。',
        parameters: Type.Object({}),
        execute: async () => {
            const calls = Array.from(callManager['activeCalls'].values()).map(c => ({
                userId: c.userId,
                roomId: c.roomId,
                status: c.status,
                liveMinutes: Math.round((Date.now() - c.startTime.getTime()) / 60000)
            }));
            return { activeCalls: calls, total: calls.length };
        }
    });

    console.log('[VoiceGateway] Agent Tools registered successfully.');

    // TODO: 定时清理任务，清除没有正常结束的僵尸连接
}
